FROM java:8-jre
WORKDIR usr/src
ADD ./target/FavGIF-Service-0.0.1-SNAPSHOT.jar /usr/src/FavGIF-Service-0.0.1-SNAPSHOT.jar
ENV MONGODB_URL2=mongodb://localhost:27017/favgif
ENTRYPOINT ["java","-jar","FavGIF-Service-0.0.1-SNAPSHOT.jar"]