image: java:11-jdk
stages:
  - test
  - build
maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test"
maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
services:
  - 'mongo:latest'
  - 'mysql:latest'
variables:
 MONGODB_URL1: mongodb://localhost:27017/feedback
 MONGODB_URL2: mongodb://localhost:27017/favgif
 MYSQL_MYURL: jdbc:mysql://localhost:3306/authenticateUser?createDatabaseIfNotExist=true&user=root&password=${MYSQL_ROOT_PASSWORD}
 MYSQL_ROOT_PASSWORD: ilovetotravel@2021