FROM java:8-jre
WORKDIR usr/src
ADD ./target/Feedback-Service-0.0.1-SNAPSHOT.jar /usr/src/Feedback-Service-0.0.1-SNAPSHOT.jar
ENV MONGODB_URL1=mongodb://localhost:27017/feedback
ENTRYPOINT ["java","-jar","Feedback-Service-0.0.1-SNAPSHOT.jar"]