FROM java:8-jre
WORKDIR usr/src
ADD ./target/UserAuthentication-Service-0.0.1-SNAPSHOT.jar /usr/src/UserAuthentication-Service-0.0.1-SNAPSHOT.jar
ENV MYSQL_MYURL=jdbc:mysql://localhost:3306/authenticateUser?createDatabaseIfNotExist=true&user=root&password=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_ROOT_PASSWORD=Ekt@toshi25
ENTRYPOINT ["java","-jar","UserAuthentication-Service-0.0.1-SNAPSHOT.jar"]